[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "matrix"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = ["torch", "megadna", "notebook"]

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = ["pre-commit", "ruff"]

[tool.hatch.build.targets.wheel]
packages = ["src/matrix", "megaDNA"]

[tool.uv.sources]
torch = { url = "https://download.pytorch.org/whl/cu126/torch-2.6.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl" }
megadna = { path = "megaDNA" }
